//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行库版本:2.0.50727.3623
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 此源代码是由 Microsoft.VSDesigner 2.0.50727.3623 版自动生成。
// 
#pragma warning disable 1591

namespace Admin.SQLServerDAL.ERPWebSer {
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    using System.Data;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ServiceSoap", Namespace="http://192.168.3.109/")]
    public partial class Service : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback OLEDBQueryProductOperationCompleted;
        
        private System.Threading.SendOrPostCallback OLEDBQueryDispatchOrderOperationCompleted;
        
        private System.Threading.SendOrPostCallback OLEDBQueryDispatchOrderDetailOperationCompleted;
        
        private System.Threading.SendOrPostCallback OLEDBQueryProductDetailOperationCompleted;
        
        private System.Threading.SendOrPostCallback OLEDBQueryBOMOperationCompleted;
        
        private System.Threading.SendOrPostCallback OLEDBQueryWireDetailOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Service() {
            this.Url = global::Admin.SQLServerDAL.Properties.Settings.Default.Admin_SQLServerDAL_ERPWebSer_Service;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event OLEDBQueryProductCompletedEventHandler OLEDBQueryProductCompleted;
        
        /// <remarks/>
        public event OLEDBQueryDispatchOrderCompletedEventHandler OLEDBQueryDispatchOrderCompleted;
        
        /// <remarks/>
        public event OLEDBQueryDispatchOrderDetailCompletedEventHandler OLEDBQueryDispatchOrderDetailCompleted;
        
        /// <remarks/>
        public event OLEDBQueryProductDetailCompletedEventHandler OLEDBQueryProductDetailCompleted;
        
        /// <remarks/>
        public event OLEDBQueryBOMCompletedEventHandler OLEDBQueryBOMCompleted;
        
        /// <remarks/>
        public event OLEDBQueryWireDetailCompletedEventHandler OLEDBQueryWireDetailCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://192.168.3.109/OLEDBQueryProduct", RequestNamespace="http://192.168.3.109/", ResponseNamespace="http://192.168.3.109/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet OLEDBQueryProduct(string StrWhere) {
            object[] results = this.Invoke("OLEDBQueryProduct", new object[] {
                        StrWhere});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void OLEDBQueryProductAsync(string StrWhere) {
            this.OLEDBQueryProductAsync(StrWhere, null);
        }
        
        /// <remarks/>
        public void OLEDBQueryProductAsync(string StrWhere, object userState) {
            if ((this.OLEDBQueryProductOperationCompleted == null)) {
                this.OLEDBQueryProductOperationCompleted = new System.Threading.SendOrPostCallback(this.OnOLEDBQueryProductOperationCompleted);
            }
            this.InvokeAsync("OLEDBQueryProduct", new object[] {
                        StrWhere}, this.OLEDBQueryProductOperationCompleted, userState);
        }
        
        private void OnOLEDBQueryProductOperationCompleted(object arg) {
            if ((this.OLEDBQueryProductCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.OLEDBQueryProductCompleted(this, new OLEDBQueryProductCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://192.168.3.109/OLEDBQueryDispatchOrder", RequestNamespace="http://192.168.3.109/", ResponseNamespace="http://192.168.3.109/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet OLEDBQueryDispatchOrder(string StrWhere) {
            object[] results = this.Invoke("OLEDBQueryDispatchOrder", new object[] {
                        StrWhere});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void OLEDBQueryDispatchOrderAsync(string StrWhere) {
            this.OLEDBQueryDispatchOrderAsync(StrWhere, null);
        }
        
        /// <remarks/>
        public void OLEDBQueryDispatchOrderAsync(string StrWhere, object userState) {
            if ((this.OLEDBQueryDispatchOrderOperationCompleted == null)) {
                this.OLEDBQueryDispatchOrderOperationCompleted = new System.Threading.SendOrPostCallback(this.OnOLEDBQueryDispatchOrderOperationCompleted);
            }
            this.InvokeAsync("OLEDBQueryDispatchOrder", new object[] {
                        StrWhere}, this.OLEDBQueryDispatchOrderOperationCompleted, userState);
        }
        
        private void OnOLEDBQueryDispatchOrderOperationCompleted(object arg) {
            if ((this.OLEDBQueryDispatchOrderCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.OLEDBQueryDispatchOrderCompleted(this, new OLEDBQueryDispatchOrderCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://192.168.3.109/OLEDBQueryDispatchOrderDetail", RequestNamespace="http://192.168.3.109/", ResponseNamespace="http://192.168.3.109/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet OLEDBQueryDispatchOrderDetail(string StrWhere) {
            object[] results = this.Invoke("OLEDBQueryDispatchOrderDetail", new object[] {
                        StrWhere});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void OLEDBQueryDispatchOrderDetailAsync(string StrWhere) {
            this.OLEDBQueryDispatchOrderDetailAsync(StrWhere, null);
        }
        
        /// <remarks/>
        public void OLEDBQueryDispatchOrderDetailAsync(string StrWhere, object userState) {
            if ((this.OLEDBQueryDispatchOrderDetailOperationCompleted == null)) {
                this.OLEDBQueryDispatchOrderDetailOperationCompleted = new System.Threading.SendOrPostCallback(this.OnOLEDBQueryDispatchOrderDetailOperationCompleted);
            }
            this.InvokeAsync("OLEDBQueryDispatchOrderDetail", new object[] {
                        StrWhere}, this.OLEDBQueryDispatchOrderDetailOperationCompleted, userState);
        }
        
        private void OnOLEDBQueryDispatchOrderDetailOperationCompleted(object arg) {
            if ((this.OLEDBQueryDispatchOrderDetailCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.OLEDBQueryDispatchOrderDetailCompleted(this, new OLEDBQueryDispatchOrderDetailCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://192.168.3.109/OLEDBQueryProductDetail", RequestNamespace="http://192.168.3.109/", ResponseNamespace="http://192.168.3.109/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet OLEDBQueryProductDetail(string StrWhere) {
            object[] results = this.Invoke("OLEDBQueryProductDetail", new object[] {
                        StrWhere});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void OLEDBQueryProductDetailAsync(string StrWhere) {
            this.OLEDBQueryProductDetailAsync(StrWhere, null);
        }
        
        /// <remarks/>
        public void OLEDBQueryProductDetailAsync(string StrWhere, object userState) {
            if ((this.OLEDBQueryProductDetailOperationCompleted == null)) {
                this.OLEDBQueryProductDetailOperationCompleted = new System.Threading.SendOrPostCallback(this.OnOLEDBQueryProductDetailOperationCompleted);
            }
            this.InvokeAsync("OLEDBQueryProductDetail", new object[] {
                        StrWhere}, this.OLEDBQueryProductDetailOperationCompleted, userState);
        }
        
        private void OnOLEDBQueryProductDetailOperationCompleted(object arg) {
            if ((this.OLEDBQueryProductDetailCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.OLEDBQueryProductDetailCompleted(this, new OLEDBQueryProductDetailCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://192.168.3.109/OLEDBQueryBOM", RequestNamespace="http://192.168.3.109/", ResponseNamespace="http://192.168.3.109/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet OLEDBQueryBOM(string StrWhere) {
            object[] results = this.Invoke("OLEDBQueryBOM", new object[] {
                        StrWhere});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void OLEDBQueryBOMAsync(string StrWhere) {
            this.OLEDBQueryBOMAsync(StrWhere, null);
        }
        
        /// <remarks/>
        public void OLEDBQueryBOMAsync(string StrWhere, object userState) {
            if ((this.OLEDBQueryBOMOperationCompleted == null)) {
                this.OLEDBQueryBOMOperationCompleted = new System.Threading.SendOrPostCallback(this.OnOLEDBQueryBOMOperationCompleted);
            }
            this.InvokeAsync("OLEDBQueryBOM", new object[] {
                        StrWhere}, this.OLEDBQueryBOMOperationCompleted, userState);
        }
        
        private void OnOLEDBQueryBOMOperationCompleted(object arg) {
            if ((this.OLEDBQueryBOMCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.OLEDBQueryBOMCompleted(this, new OLEDBQueryBOMCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://192.168.3.109/OLEDBQueryWireDetail", RequestNamespace="http://192.168.3.109/", ResponseNamespace="http://192.168.3.109/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet OLEDBQueryWireDetail() {
            object[] results = this.Invoke("OLEDBQueryWireDetail", new object[0]);
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void OLEDBQueryWireDetailAsync() {
            this.OLEDBQueryWireDetailAsync(null);
        }
        
        /// <remarks/>
        public void OLEDBQueryWireDetailAsync(object userState) {
            if ((this.OLEDBQueryWireDetailOperationCompleted == null)) {
                this.OLEDBQueryWireDetailOperationCompleted = new System.Threading.SendOrPostCallback(this.OnOLEDBQueryWireDetailOperationCompleted);
            }
            this.InvokeAsync("OLEDBQueryWireDetail", new object[0], this.OLEDBQueryWireDetailOperationCompleted, userState);
        }
        
        private void OnOLEDBQueryWireDetailOperationCompleted(object arg) {
            if ((this.OLEDBQueryWireDetailCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.OLEDBQueryWireDetailCompleted(this, new OLEDBQueryWireDetailCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    public delegate void OLEDBQueryProductCompletedEventHandler(object sender, OLEDBQueryProductCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class OLEDBQueryProductCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal OLEDBQueryProductCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    public delegate void OLEDBQueryDispatchOrderCompletedEventHandler(object sender, OLEDBQueryDispatchOrderCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class OLEDBQueryDispatchOrderCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal OLEDBQueryDispatchOrderCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    public delegate void OLEDBQueryDispatchOrderDetailCompletedEventHandler(object sender, OLEDBQueryDispatchOrderDetailCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class OLEDBQueryDispatchOrderDetailCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal OLEDBQueryDispatchOrderDetailCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    public delegate void OLEDBQueryProductDetailCompletedEventHandler(object sender, OLEDBQueryProductDetailCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class OLEDBQueryProductDetailCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal OLEDBQueryProductDetailCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    public delegate void OLEDBQueryBOMCompletedEventHandler(object sender, OLEDBQueryBOMCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class OLEDBQueryBOMCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal OLEDBQueryBOMCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    public delegate void OLEDBQueryWireDetailCompletedEventHandler(object sender, OLEDBQueryWireDetailCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class OLEDBQueryWireDetailCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal OLEDBQueryWireDetailCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591